import { createServer } from 'node:http';
import { createHmac, timingSafeEqual, randomUUID } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, normalize } from 'node:path';

const root=process.cwd(),dataDir=join(root,'data'),settingsFile=join(dataDir,'settings.json'),ordersFile=join(dataDir,'orders.json');
const fallback={pickup:'TG Factory #4',shipping:{'Phnom Penh':'$2.00','Other provinces':'$3.50','Remote areas':'$5.00'}};
if(!existsSync(dataDir))mkdirSync(dataDir);if(!existsSync(settingsFile))writeFileSync(settingsFile,JSON.stringify(fallback,null,2));if(!existsSync(ordersFile))writeFileSync(ordersFile,'[]');
const json=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(body))};
const readBody=req=>new Promise((resolve,reject)=>{let body='';req.on('data',chunk=>{body+=chunk;if(body.length>1e6)reject(Error('Request too large'))});req.on('end',()=>{try{resolve(JSON.parse(body||'{}'))}catch{reject(Error('Invalid JSON'))}})});
function validInitData(initData){if(process.env.ALLOW_DEMO_ORDERS==='true'&&!initData)return {id:'demo-user'};if(!process.env.BOT_TOKEN||!initData)return null;const p=new URLSearchParams(initData),hash=p.get('hash');if(!hash)return null;p.delete('hash');const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const secret=createHmac('sha256','WebAppData').update(process.env.BOT_TOKEN).digest();const expected=createHmac('sha256',secret).update(check).digest('hex');if(hash.length!==expected.length||!timingSafeEqual(Buffer.from(hash),Buffer.from(expected)))return null;try{return JSON.parse(p.get('user'))}catch{return null}}
async function sendQr(chatId,order){if(!process.env.BOT_TOKEN||!process.env.PAYMENT_QR_FILE_ID)return;const caption=`Payment QR / QR កូដបង់ប្រាក់\n\nOrder: ${order.id}\nTotal: $${order.total.toFixed(2)}\n${order.delivery==='pickup'?'Pickup':'Delivery'}\n\nPlease pay the exact amount, then send your payment proof in this chat.\nសូមបង់ចំនួនទឹកប្រាក់ឲ្យត្រឹមត្រូវ ហើយផ្ញើភស្តុតាងការបង់ប្រាក់ក្នុងការជជែកនេះ។`;await fetch(`https://api.telegram.org/bot${process.env.BOT_TOKEN}/sendPhoto`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chatId,photo:process.env.PAYMENT_QR_FILE_ID,caption})});}
const server=createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');try{if(req.method==='GET'&&url.pathname==='/api/settings')return json(res,200,JSON.parse(readFileSync(settingsFile)));if(req.method==='PUT'&&url.pathname==='/api/settings'){if(!process.env.ADMIN_KEY||req.headers['x-admin-key']!==process.env.ADMIN_KEY)return json(res,401,{error:'Unauthorized'});const s=await readBody(req);if(!s.pickup||!s.shipping)return json(res,400,{error:'Invalid settings'});writeFileSync(settingsFile,JSON.stringify(s,null,2));return json(res,200,s)}if(req.method==='POST'&&url.pathname==='/api/orders'){const input=await readBody(req),user=validInitData(input.telegramInitData);if(!user)return json(res,401,{error:'Open this checkout from the Telegram Mini App.'});if(!Array.isArray(input.items)||!input.items.length||!Number.isFinite(input.total))return json(res,400,{error:'Invalid order'});const order={id:`CYP-${randomUUID().slice(0,8).toUpperCase()}`,createdAt:new Date().toISOString(),telegramUserId:user.id,name:input.name,contact:input.contact,address:input.address||'',delivery:input.delivery,region:input.region||'',items:input.items,subtotal:input.subtotal,shipping:input.shipping,total:input.total,status:'awaiting_payment'};const orders=JSON.parse(readFileSync(ordersFile));orders.unshift(order);writeFileSync(ordersFile,JSON.stringify(orders,null,2));await sendQr(user.id,order);return json(res,201,{id:order.id})}if(req.method==='GET'){const requested=normalize(url.pathname==='/'?'/index.html':url.pathname).replace(/^([.][.][/\\])+/,''),file=join(root,requested);if(!file.startsWith(root)||!existsSync(file))return json(res,404,{error:'Not found'});const ext=file.split('.').pop(),type={html:'text/html; charset=utf-8',js:'text/javascript; charset=utf-8',css:'text/css; charset=utf-8'}[ext]||'application/octet-stream';res.writeHead(200,{'content-type':type});return res.end(readFileSync(file));}json(res,405,{error:'Method not allowed'});}catch(error){json(res,500,{error:error.message})}});
server.listen(process.env.PORT||3000,()=>console.log(`Cypress store running on http://localhost:${process.env.PORT||3000}`));
